### ISSUE TITLE
NTM space overwrites the botania's garden of glass sky in the overworld with no way to disable it

### ISSUE THREAD

**Issue by brandyyn** [JameH2/Hbm-s-Nuclear-Tech-GIT#123]
NTM space overwrites the botania's garden of glass sky in the overworld with no way to disable it

i have this set to false:
![image](https://github.com/user-attachments/assets/f21d9db8-21c5-4503-bdb6-9688539ef086)

**Comment by brandyyn** [comment]
FIX IT PLEASEEE 
![image](https://github.com/user-attachments/assets/036650fb-6933-426a-aea6-13615189b345)

**Comment by SuperTechxter** [comment]
space is cooler deal with it 😎

**Comment by brandyyn** [comment]
> space is cooler deal with it 😎

its literally the default mc skybox with a glitchy satellite jumping around and disappearing and reappearing constantly. i prefer botania :3

**Comment by MellowArpeggiation** [comment]
I've noticed issues with satellite jerkiness in multiplayer (fix incoming), but not in singleplayer, are you in singleplayer? Also the skybox merely _mimics_ the default MC skybox, if you change the atmospheric composition it'll change dramatically. Since we effectively reimplement the entire skybox, the chainloader can't work. The config option remaining is an oversight however, so I'll fix that up.

**Comment by brandyyn** [comment]
> I've noticed issues with satellite jerkiness in multiplayer (fix incoming), but not in singleplayer, are you in singleplayer? Also the skybox merely _mimics_ the default MC skybox, if you change the atmospheric composition it'll change dramatically. Since we effectively reimplement the entire skybox, the chainloader can't work. The config option remaining is an oversight however, so I'll fix that up.

yeah, i'm in singleplayer. 

I don't like the satellite in my skybox regardless, nor do I like the default MC skybox- the config should remain. You can still do all your fancy sky box things on other planets because the Botania Skybox only affects the overworld, and furthermore I believe this will also break optifine's custom sky and notfine/mcpf's custom sky?

**Comment by MellowArpeggiation** [comment]
Again, not an option, if you change the atmospheric composition of the Earth, but the skybox remains a cool blue, you'll suffocate with no indication as to why. We could add configs to the satellite visibility but I'd rather fix the jerkiness beforehand. How much we can improve skybox compat will depend on how other mods have implemented theirs, so I'll investigate.

**Comment by brandyyn** [comment]
> Again, not an option, if you change the atmospheric composition of the Earth, but the skybox remains a cool blue, you'll suffocate with no indication as to why. We could add configs to the satellite visibility but I'd rather fix the jerkiness beforehand. How much we can improve skybox compat will depend on how other mods have implemented theirs, so I'll investigate.

Well if you can implement a cooler looking skybox than normal MC, that would be cool too. I just don't want to lose a cool skybox over practically nothing in my case.

Can you even change the atmospheric composition of Earth in survival?

**Comment by MellowArpeggiation** [comment]
Yes, as demonstrated in another issue (#125), terraforming is already possible, with more machines planned to make the process even more accessible, depending on your tech level.

**Comment by brandyyn** [comment]
> Yes, as demonstrated in another issue (#125), terraforming is already possible, with more machines planned to make the process even more accessible, depending on your tech level.

lovely. I pray for a cool skybox of Earth in the future. Please :)

**Comment by brandyyn** [comment]
> Again, not an option, if you change the atmospheric composition of the Earth, but the skybox remains a cool blue, you'll suffocate with no indication as to why. We could add configs to the satellite visibility but I'd rather fix the jerkiness beforehand. How much we can improve skybox compat will depend on how other mods have implemented theirs, so I'll investigate.

@MellowArpeggiation 

https://streamable.com/3hgf9v

https://streamable.com/uqyqza

**Comment by MellowArpeggiation** [comment]
Thanks for the demonstration, I'm assuming that's on the latest version (x5074)?

**Comment by brandyyn** [comment]
> Thanks for the demonstration, I'm assuming that's on the latest version (x5074)?

Yes. I also just don't like the satellite at all and would prefer to just disable it. It's ugly and distracting and way too fast

**Comment by MellowArpeggiation** [comment]
Thanks for the input, I wouldn't hold your breath on their removal though.

**Comment by brandyyn** [comment]
> Thanks for the input, I wouldn't hold your breath on their removal though.

Literally just a config option…

**Comment by MellowArpeggiation** [comment]
I am becoming less inclined to help you the more you bellyache about a moving dot. I have slowed down the satellites a touch and implemented an entirely new timing system that uses your system time rather than the in-game ticks+partials which introduces judder on fast objects. It should now be perfectly smooth regardless of network conditions, mod interactions, and anything else, this will be end of this matter.

I'm leaving this issue open to remind myself to work on skybox compat, I will consider more configuration options in the future.

**Comment by MellowArpeggiation** [comment]
Botania support is unlikely, we'd have to reimplement the entire Botania skybox ourselves while removing the Botania planets and the moon (since we draw all that ourselves), leaving behind only the rainbow and the stars; At which point you only have a rainbow - which interacts very oddly with view-bobbing due to it rendering way too close to the player - and colorful stars, which can be done in NTM: Space with a resource pack targeting `hbm:textures/misc/space/night.png`
